using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TruthDetection.BLL.Dtos
{
    public class AddFileDto  // upload / update 
    {

        [Required]
        public string ID { get; set; } //string generated by guid 

        [Required]
        public IFormFile File { get; set; }
    }
}
