using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TruthDetection.BLL.Dtos
{
    public class DeleteFileDto
    {

        [Required]
        public string ID { get; set; } //string generated by guid 

        [Required]
        public string FileName { get; set; }  // filename of image using guid 

        [Required]
        public string FolderName { get; set; }// Images or videos 
    }
}
