using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TruthDetection.BLL.Dtos
{
    public class ShowVideoDto
    {
        [Required]
        public string UserId { get; set; }  // generated by guid 

        [Required]
        public int VideoId { get; set; }

        [Required]
        public string VideoName { get; set; }
    }
}
