using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TruthDetection.BLL.Dtos
{
    public class ShowFileDto
    {

        [Required]
        public string ID { get; set; } //string generated by guid 

        [Required]
        public string ImageName { get; set; }

    }
}
